# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++

# Dependencies
install:
   - sudo apt-get install libgtest-dev

# Build steps
script:
  - mkdir build && cd build
  - cmake -Dtest=ON .. && make
  - ./mips_test
