# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++
  - clang

os:
    - linux
    - osx

# Build steps
script:
  - mkdir build && cd build
  - cmake -Dtest=ON .. && make
  - gdb mips_test
  - run
  - bt
  - q
  - y
  - ./mips_test
