# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++

os:
    - linux
    - osx
    - windows

# Build steps
script:
  - mkdir build && cd build
  - cmake -Dtest=ON .. && make
  - ./mips_test
